#Datoteka za uporabniski umesnik    115 120

#zazenemo potrebne datoteke
source("../libraries/lib.R")
source("../osnova/osnovne_funkcije.r")
source("../modeli/igra_zivljenja.r")
source("../modeli/igra_zivljenja_vec.r")
source("../modeli/cakalne_vrste.r")
source("../vizualizacija/animacija.r")
source("../modeli/posebne_matrike.r")



sidebar <- dashboardSidebar(hr(),
                            #tukaj je opisan stranski meni, ki se lahko spravi
                            sidebarMenu(id = "zacetek",
                                        menuItem("Uvod",
                                                 tabName = "zacetek", selected = TRUE,
                                                 icon = tags$i(class="fas fa-play-circle"))),
                            sidebarMenu(id="osnova",
                                        menuItem("Rojstno-smrtni procesi",
                                                 tabName = "osnove",
                                                 icon = tags$i(class="fas fa-user-alt-slash"))),
                            sidebarMenu(id="igra",
                                        menuItem("Igra življenja",tabName = "igre",
                                                 icon = tags$i(class="fas fa-heartbeat"))),
                            sidebarMenu(id="celica",
                                        menuItem("Zakaj je pomembno?",tabName = "pomen",
                                                 icon = tags$i(class="fas fa-exclamation"))),
                            sidebarMenu(id="vrsta",
                                        menuItem("Posebni primeri",tabName = "vrste",
                                                 icon = tags$i(class="fas fa-surprise")))
)


body <- dashboardBody(
  tabItems(
    tabItem(tabName = "zacetek",
            mainPanel(
              includeMarkdown("igra.md"))
    ),
    tabItem(tabName = "osnove",
            #problemi, ki jih imam tukaj so prikaz unused arguments v shiny vmesniku
            fluidRow(sidebarPanel(
              p("Tu izberemo parametre rojstno smrtnega procesa"),
              numericInput("zacetno2",
                           "Velikost zacetne populacije:",
                           min = 0,
                           max = 100,
                           value = 3,
                           step = 1),
              p("Velikost začetne populacije vpliva na hitrost izumrtja."),
              numericInput("st_korakov2",
                           "Koliko korakov želimo, da simulacija naredi:",
                           min = 0,
                           max = 10000,
                           value = 10,
                           step = 1),
              p("Število korakov nam bo povedalo, kako daleč v prihodnost vidimo."),
              selectInput("st_rojstvo2", 
                          label = "Porazdelitev rojstev v modelu",
                          c("Normalna" = 1, 
                            "Eksponentna" = 2,
                            "Cauchyeva" = 3, 
                            "Lognormalna" = 4)),
              p("Izberemo porazdelitev rojstev."),
              selectInput("st_smrt2", 
                          label = "Porazdelitev smrti v modelu",
                          c("Normalna" = 1, 
                            "Eksponentna" = 2,
                            "Cauchyeva" = 3, 
                            "Lognormalna" = 4)),
              p("Izberemo porazdelitev smrti."),
              actionButton("go2", "Poglejmo si prikaz")),
              mainPanel(# includeMarkdown("rojstno.md"),
                p("Da bomo razumeli delovanje igre življenja, moramo najprej razumeti rojstno smrtne procese. Vsak si lahko tu sam izbere, kakšen proces bo začel. Izberi si porazdelitev smrti in porazdelitev rojstev in opazuj spremembe,
                         ki jih graf prikaže. Vidimo, da so porazdelitve zelo pomembne, 
                         prav tako pa vpliva velikost začetne populacije."),
                p("Ko v levem oknu izberemo vse potrebne parametre, kliknemo gumb poglejmo si prikaz.
                         Ko se nam pojavi okno z grafom lahko kliknemo gumb Play, ki bo zagnal potek procesa.
                         Prav tako lahko z drsnikom to premaknemo sami."),
                uiOutput("animacija")))
    ),
    tabItem(tabName = "igre",
            fluidRow(sidebarPanel(
              numericInput("st_korakov_igra",
                           "Zanima nas igra v koraku številka:",
                           min = 2,
                           max = 10000,
                           value = 10,
                           step = 1),
              p("Tukaj določimo korak, v katerem bomo pogledali igro"),
              numericInput("vrstice_igre",
                           "Koliko vrstic naj bo imela igra:",
                           min = 2,
                           max = 10000,
                           value = 10,
                           step = 1),
              numericInput("stolpci_igre",
                           "Koliko stolpcev naj bo imela igra:",
                           min = 2,
                           max = 10000,
                           value = 10,
                           step = 1),
              p("S stolpci in vrsticami določimo dimenzijo igre."),
              actionButton("matrika", "Pridobi matriko"),
              actionButton("go", "Poglejmo si igro")
            ),
            mainPanel(p("Ideja Johna Conwaya je bila prikazati, kako v zaprtem prostoru deluje 
                        delitev celic. Navadno nas zanima kako se igra ponavlja oziroma kako se konča.
                        Zato bomo pogledali kako se naša matrika obnaša na korakih, ki smo jih pogledali."),
                      p("Naravna vprašanja življenja so kdaj se bo le to končalo, in ali se bo kaj ponovilo.
                        No v tem primeru lahko hitro vidimo, da ponavljanje pomeni, da se igra ne bo končala.
                        Imamo namreč determinističen model, ki ne bo nikoli spremenil svojih pravil. Tako bomo
                         iz iste začetne matrike vedno dobili enak rezultat. Če se igra konča pa je resnica drugačna.
                        V tem primeru bo namreč veljalo, da se v vsakem naslednjem krogu igra ponavlja in sicer s
                         s periodo 1. Lahko bi torej rekli, da ponavljanje negira zaključek, zaključek pa
                         implicira ponavljanje."),
                      p("V stranskem meniju z gumboma za velikost matrike določimo dimenzije matrike,
                        nato pa kliknemo gumb pridobi matriko. Ko imamo matriko zbrano, lahko spreminjamo
                        v katerem koraku nas igra zanima."),
                      p("Da si ogledamo igro v poljubnem koraku kliknemo gumb Oglejmo si igro."),
                      p("Vsakič, ko želimo pogledati novo začetno matriko kliknemo gumb pridobi matriko, 
                      sicer pa ta gumb ni pomemben."),
                      textOutput("konec"),
                      textOutput("ponovno"),
                      plotOutput("celotna_igra"),
                      plotOutput("narisi_zacetno"),
                      p("Ogledamo si lahko kako izgleda igra v izbranem koraku.")))),
    tabItem(tabName = "pomen",
            mainPanel(
              includeMarkdown("celica.md"))
    ),
    tabItem(tabName = "vrste",
            mainPanel(
              tabsetPanel(
                tabPanel("Navodila",
                         p("Uporaba je sledeča:"),
                         p("Da pogledamo različne korake, bomo spreminjali število korakov,
                         saj nam bo funckija vedno vrnila zadnji označen korak.")),
                tabPanel("Drsalec",
                         sidebarPanel(numericInput("koraki_drsi",
                                                   "Koliko korakov bo igra imela:",
                                                   min = 2,
                                                   max = 10000,
                                                   value = 10,
                                                   step = 1)),
                         mainPanel(textOutput("stetje_drsi"),
                                   textOutput("ponovno_drsi"),
                                   plotOutput("drsi"),
                                   plotOutput("narisi_zacetno_drsi")
                         )),
                tabPanel("Gosper",
                         sidebarPanel(numericInput("koraki_gosi",
                                                   "Koliko korakov bo igra imela:",
                                                   min = 2,
                                                   max = 10000,
                                                   value = 10,
                                                   step = 1)),
                         mainPanel(textOutput("stetje_gosi"),
                                   textOutput("ponovno_gosi"),
                                   plotOutput("gosi"),
                                   plotOutput("narisi_zacetno_gos")
                         )),
                tabPanel("Krastača",
                         sidebarPanel(numericInput("koraki_zaba",
                                                   "Koliko korakov bo igra imela:",
                                                   min = 2,
                                                   max = 10000,
                                                   value = 10,
                                                   step = 1)),
                         mainPanel(textOutput("stetje_toad"),
                                   textOutput("ponovno_toad"),
                                   plotOutput("zabica"),
                                   plotOutput("narisi_zacetno_toad")
                         )),
                tabPanel("Ladja",
                         sidebarPanel(numericInput("koraki_morje",
                                                   "Koliko korakov bo igra imela:",
                                                   min = 2,
                                                   max = 10000,
                                                   value = 10,
                                                   step = 1)),
                         mainPanel(textOutput("stetje_ladjon"),
                                   textOutput("ponovno_ladjon"),
                                   plotOutput("ladjica"),
                                   plotOutput("narisi_zacetno_ladja")
                         )),
                tabPanel("Neomejeno",
                         sidebarPanel(numericInput("koraki_rast",
                                                   "Koliko korakov bo igra imela:",
                                                   min = 2,
                                                   max = 10000,
                                                   value = 10,
                                                   step = 1)),
                         mainPanel(textOutput("stetje_rast"),
                                   textOutput("ponovno_rast"),
                                   plotOutput("rastica"),
                                   plotOutput("narisi_zacetno_rast")
                         )),
                tabPanel("Motor",
                         sidebarPanel(numericInput("koraki_brum",
                                                   "Koliko korakov bo igra imela:",
                                                   min = 2,
                                                   max = 10000,
                                                   value = 10,
                                                   step = 1)),
                         mainPanel(textOutput("stetje_brum"),
                                   textOutput("ponovno_brum"),
                                   plotOutput("motorcek"),
                                   plotOutput("narisi_zacetno_brum")
                         )),
                tabPanel("Pištola",
                         sidebarPanel(numericInput("koraki_bum",
                                                   "Koliko korakov bo igra imela:",
                                                   min = 2,
                                                   max = 10000,
                                                   value = 10,
                                                   step = 1)),
                         mainPanel(textOutput("stetje_bum"),
                                   textOutput("ponovno_bum"),
                                   plotOutput("pistolica"),
                                   plotOutput("narisi_zacetno_bum")
                         )),
                tabPanel("Pentomino",
                         sidebarPanel(numericInput("koraki_pet",
                                                   "Koliko korakov bo igra imela:",
                                                   min = 2,
                                                   max = 10000,
                                                   value = 10,
                                                   step = 1)),
                         mainPanel(textOutput("stetje_pet"),
                                   textOutput("ponovno_pet"),
                                   plotOutput("petica"),
                                   plotOutput("narisi_zacetno_pet")
                         )),
                tabPanel("Pulsar",
                         sidebarPanel(numericInput("koraki_pulz",
                                                   "Koliko korakov bo igra imela:",
                                                   min = 2,
                                                   max = 10000,
                                                   value = 10,
                                                   step = 1)),
                         mainPanel(textOutput("stetje_pulz"),
                                   textOutput("ponovno_pulz"),
                                   plotOutput("pulzek"),
                                   plotOutput("narisi_zacetno_pulz")
                         )),
                # tabPanel("Statično",
                #          sidebarPanel(numericInput("koraki_statika1",
                #                                    "Koliko korakov bo igra imela:",
                #                                    min = 2,
                #                                    max = 10000,
                #                                    value = 10,
                #                                    step = 1),
                #                       numericInput("koraki_statika2",
                #                                    "Koliko korakov bo igra imela:",
                #                                    min = 2,
                #                                    max = 10000,
                #                                    value = 10,
                #                                    step = 1),
                #                       numericInput("koraki_statika3",
                #                                    "Koliko korakov bo igra imela:",
                #                                    min = 2,
                #                                    max = 10000,
                #                                    value = 10,
                #                                    step = 1)),
                #          mainPanel(textOutput("stetje_statika1"),
                #                    textOutput("ponovno_statika1"),
                #                    plotOutput("staticnost1a"),
                #                    textOutput("stetje_statika2"),
                #                    textOutput("ponovno_statika2"),
                #                    plotOutput("staticnost2a"),
                #                    textOutput("stetje_statika3"),
                #                    textOutput("ponovno_statika3"),
                #                    plotOutput("staticnost3a")
                #          )),
                tabPanel("Svetilnik",
                         sidebarPanel(numericInput("koraki_luc",
                                                   "Koliko korakov bo igra imela:",
                                                   min = 2,
                                                   max = 10000,
                                                   value = 10,
                                                   step = 1)),
                         mainPanel(textOutput("stetje_luc"),
                                   textOutput("ponovno_luc"),
                                   plotOutput("lucka"),
                                   plotOutput("narisi_zacetno_luc")
                         )),
                #tukaj bo več plotov, več napisano),
                tabPanel("Umri pokončno",
                         sidebarPanel(numericInput("koraki_DH",
                                                   "Koliko korakov bo igra imela:",
                                                   min = 2,
                                                   max = 10000,
                                                   value = 10,
                                                   step = 1)),
                         mainPanel(textOutput("stetje_DH"),
                                   textOutput("ponovno_DH"),
                                   plotOutput("DH1"),
                                   plotOutput("narisi_zacetno_DH")
                         )),
                tabPanel("Utripajoča lučka",
                         sidebarPanel(numericInput("koraki_blip",
                                                   "Koliko korakov bo igra imela:",
                                                   min = 2,
                                                   max = 10000,
                                                   value = 10,
                                                   step = 1)),
                         mainPanel(textOutput("stetje_blip"),
                                   textOutput("ponovno_blip"),
                                   plotOutput("blip"),
                                   plotOutput("narisi_zacetno_blip")
                         )),
                tabPanel("Vesoljska ladja",
                         sidebarPanel(numericInput("koraki_vroom",
                                                   "Koliko korakov bo igra imela:",
                                                   min = 2,
                                                   max = 10000,
                                                   value = 10,
                                                   step = 1)),
                         mainPanel(textOutput("stetje_vroom"),
                                   textOutput("ponovno_vroom"),
                                   plotOutput("vroom_vroom"),
                                   plotOutput("narisi_zacetno_vroom")
                         )),
                tabPanel("Želod",icon = tags$i(class="fas fa-acorn"),
                         sidebarPanel(numericInput("koraki_hrast",
                                                   "Koliko korakov bo igra imela:",
                                                   min = 2,
                                                   max = 10000,
                                                   value = 10,
                                                   step = 1)),
                         mainPanel(textOutput("stetje_hrast"),
                                   textOutput("ponovno_hrast"),
                                   plotOutput("hrastek"),
                                   plotOutput("narisi_zacetno_hrast")
                         ))
              )
            ))
  )
)


fluidPage(useShinyjs(),
          dashboardPage(
            dashboardHeader(title = "Igra življenja",
                            tags$li(class = "dropdown",
                                    tags$li(class = "dropdown", textOutput("dashboardLoggedUser"), style = "padding-top: 15px; padding-bottom: 15px; color: #fff;"),
                                    tags$li(class = "dropdown", actionLink("dashboardLogin", textOutput("logintext")))
                            )),
            sidebar,
            body,
            skin = "red"),
          theme="bootstrap.css"
)